istsos:
  db: blockchain
  url: https://chain.softlab.ntua.gr/istsos/
  ip: chain.softlab.ntua.gr
node:
  '8501': Attica
  '8502': Crete
  '8503': Islands
current:
  port: '8502'
  url: http://127.0.0.1:8502
