istsos:
  db: blockchain
  ip: 192.168.2.13
  url: http://192.168.2.13/istsos/
meteo:
  stations: external_data/stations_list.txt
paths:
  primitive: ./firstdapp/routes/uploads/
  read: read_data/
  unread: unread_data/
